#!/usr/bin/env python3

import sys
from PIL import ImageFont, Image, ImageDraw

FIRST = 0x20
LAST  = 0x7E

def packbits(data):
    """PackBits RLE (Apple/TIFF). Decoded by font_decode() in gui.c.

    Control byte n (read as signed):
      0..127   -> copy the next (n + 1) literal bytes
      -1..-127 -> repeat the next single byte (1 - n) times  (i.e. 2..128)
      -128     -> no-op (never emitted)
    Coverage atlases are mostly long runs of 0x00/0xFF, so this is a big win.
    """
    out = bytearray()
    i, n = 0, len(data)
    while i < n:

        run = 1
        while i + run < n and data[i + run] == data[i] and run < 128:
            run += 1
        if run >= 2:
            out.append((257 - run) & 0xFF)
            out.append(data[i])
            i += run
        else:

            start = i
            lit = 0
            while i < n and lit < 128 and not (i + 1 < n and data[i] == data[i + 1]):
                i += 1
                lit += 1
            out.append(lit - 1)
            out.extend(data[start:start + lit])
    return out

def main():
    ttf, px, prefix, out = sys.argv[1], int(sys.argv[2]), sys.argv[3], sys.argv[4]
    font = ImageFont.truetype(ttf, px)
    ascent, descent = font.getmetrics()
    line_height = ascent + descent

    glyphs = []
    for cp in range(FIRST, LAST + 1):
        ch = chr(cp)

        adv = int(round(font.getlength(ch)))

        bbox = font.getbbox(ch)
        if bbox is None:
            glyphs.append((cp, 0, 0, 0, 0, adv, b""))
            continue
        l, t, r, b = bbox
        w, h = max(0, r - l), max(0, b - t)
        if w == 0 or h == 0:
            glyphs.append((cp, 0, 0, 0, 0, adv, b""))
            continue
        img = Image.new("L", (w, h), 0)
        d = ImageDraw.Draw(img)

        d.text((-l, -t), ch, font=font, fill=255)
        data = img.tobytes()

        top = ascent - t
        glyphs.append((cp, w, h, l, top, adv, data))

    with open(out, "w") as f:
        f.write("// AUTO-GENERATED by tools/bake_font.py — do not edit.\n")
        f.write("use crate::font::{Font, Glyph};\n\n")

        offsets = []
        off = 0
        blob = bytearray()
        for (cp, w, h, l, top, adv, data) in glyphs:
            offsets.append(off)
            blob += data
            off += len(data)
        packed = packbits(blob)

        f.write(f"pub const {prefix.upper()}_PIXELS: &[u8] = &[\n")
        for i in range(0, len(packed), 20):
            row = ", ".join(str(b) for b in packed[i:i+20])
            f.write("    " + row + ",\n")
        if len(packed) == 0:
            f.write("    0\n")
        f.write("];\n\n")

        f.write(f"pub const {prefix.upper()}_GLYPHS: &[Glyph] = &[\n")
        for idx, (cp, w, h, l, top, adv, data) in enumerate(glyphs):
            ch_str = repr(chr(cp)) if cp != 0x5C else repr('\\')
            f.write(f"    Glyph {{ w: {w}, h: {h}, l: {l}, top: {top}, adv: {adv}, offset: {offsets[idx]} }},"
                    f" // {ch_str} 0x{cp:02X}\n")
        f.write("];\n\n")

        f.write(f"pub const {prefix.upper()}_FONT: Font = Font {{\n")
        f.write(f"    size: {px},\n")
        f.write(f"    ascent: {ascent},\n")
        f.write(f"    descent: {descent},\n")
        f.write(f"    line_height: {line_height},\n")
        f.write(f"    first_char: {FIRST},\n")
        f.write(f"    last_char: {LAST},\n")
        f.write(f"    glyphs: {prefix.upper()}_GLYPHS,\n")
        f.write(f"    pixels: {prefix.upper()}_PIXELS,\n")
        f.write(f"    packed_len: {len(packed)},\n")
        f.write(f"    unpacked_len: {len(blob)},\n")
        f.write("};\n")

    sys.stderr.write(
        f"baked {ttf} @ {px}px -> {out} "
        f"({len(blob)} bytes of glyphs, {len(packed)} packed, "
        f"{100*len(packed)//max(1,len(blob))}%)\n")

if __name__ == "__main__":
    main()
